#!/usr/bin/env bash
# Fail when the test bundle's fixtures have drifted from the server's examples.
#
# docs/ios-api-examples/*.json is the authority for what the app must decode
# (regenerated by `npx tsx scripts/app-api-examples.ts`). AdlerTests/Fixtures/ is
# a verbatim copy. A stale copy is exactly when a contract change most needs to
# be caught, so `ios/scripts/test.sh` runs this before building.
#
# Fix any difference with: ios/scripts/sync-fixtures.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$IOS_DIR/.." && pwd)"
SOURCE="$REPO_DIR/docs/ios-api-examples"
DEST="$IOS_DIR/AdlerTests/Fixtures"

if [ ! -d "$SOURCE" ]; then
  echo "error: $SOURCE not found. Run: npx tsx scripts/app-api-examples.ts" 1>&2
  exit 1
fi
if [ ! -d "$DEST" ]; then
  echo "error: $DEST not found. Run: ios/scripts/sync-fixtures.sh" 1>&2
  exit 1
fi

if ! diff -rq --exclude='.*' "$SOURCE" "$DEST"; then
  echo "" 1>&2
  echo "error: AdlerTests/Fixtures has drifted from docs/ios-api-examples." 1>&2
  echo "       Run ios/scripts/sync-fixtures.sh and re-run the tests." 1>&2
  exit 1
fi

count=$(find "$DEST" -name '*.json' | wc -l | tr -d ' ')
if [ "$count" -eq 0 ]; then
  echo "error: no fixtures in $DEST." 1>&2
  exit 1
fi
echo "fixtures in sync ($count files)"
