import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { register, save, snapshot, coachReply } from "./fixtures";
import { seedCoaching, reviewedProposal } from "./fixtures";
import { adaptiveFixture, adaptiveWorkspace } from "./adaptive-fixture";
import { addDays, dateInZone } from "../shared/journey";

test("one goal screen connects the approach, behavior, check-in, timeline, and coach", async ({ page }) => {
  await register(page);
  const state = await snapshot(page);
  const today = dateInZone("UTC");
  const data = adaptiveWorkspace(adaptiveFixture(today, addDays(today, 4)));
  await seedCoaching(page, data);
  await page.goto("/app/goals/essay");
  await expect(page.getByRole("navigation", { name: "App navigation" }).getByRole("link", { name: "Check-in", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Plan & timeline", exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Goal and current cycle" }).getByText("Outline experiment", { exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Goal and current cycle" })).toContainText("0 / 3 actions done");
  await expect(page.getByRole("region", { name: "Cycles and milestones" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Your learning journey", exact: true })).toBeVisible();
  await coachReply(page, [{ entity: "action", operation: "update", id: data.actions[0].id, parentId: null, values: JSON.stringify({ outcome: "Done", amount: 5 }) }]);
  await page.getByRole("button", { name: "Start action", exact: true }).click();
  await page.locator(".next-step-card").getByRole("link", { name: "Continue in Check-in" }).click();
  await expect(page).toHaveURL(/\/app\/check-in\?goal=essay/);
  await page.getByLabel("Message Adler").fill("I finished the outline today: five points.");
  await page.getByRole("button", { name: "Send message", exact: true }).click();
  await expect(page.locator(".coach-thread")).toContainText("Your update is saved.");
  await page.goto("/app/goals/essay");
  await page.getByText("Explore action reports by week", { exact: true }).click();
  await page.locator(".execution-action").first().locator("summary").click();
  await expect(page.locator(".execution-action").first()).toContainText("5 points recorded");
  const saved = await snapshot(page);
  expect(saved.data.actions).toHaveLength(3);
  expect(saved.data.actions.filter(a => a.outcome === "Done")).toHaveLength(1);
  expect(saved.data.goals[0].results.at(-1)?.value).toBe(0);
  await page.screenshot({ path: ".context/adaptive-goal-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.screenshot({ path: ".context/adaptive-goal-mobile.png", fullPage: true });
});

test("a legacy goal previews and accepts an upgrade on its existing screen", async ({ page }) => {
  await register(page, true);
  await page.goto("/app/goals/essays");
  await expect(page.getByRole("heading", { name: "Starting timeline", exact: true })).toBeVisible();
  const state = await snapshot(page);
  const plan = state.data.goals[0].plans[0];
  const today = dateInZone(state.data.timeZone);
  const adaptive = adaptiveFixture(today, addDays(today, 2));
  const changes = [{ entity: "plan" as const, operation: "update" as const, id: null, parentId: "essays", reason: "Connect the existing goal to observable work", values: JSON.stringify({ action: plan.action, criterion: plan.criterion, timing: plan.timing, adaptive }) }];
  const unchecked = await page.request.post("/api/proposals", { data: { summary: "Unchecked coaching", changes } });
  expect(unchecked.ok()).toBe(false);
  await reviewedProposal(page, changes, "An outline experiment for your essay");
  await page.reload();
  await expect(page.locator(".plan-adaptation")).toContainText("What we’re testing");
  expect((await snapshot(page)).data.goals[0].plans).toHaveLength(1);
  await page.getByRole("button", { name: "Accept updated plan", exact: true }).click();
  await expect(page.getByRole("region", { name: "Goal and current cycle" }).getByText("Outline experiment", { exact: true })).toBeVisible();
  const updated = await snapshot(page);
  expect(updated.data.goals[0].id).toBe("essays");
  expect(updated.data.goals[0].plans).toHaveLength(2);
  expect(updated.data.goals[0].results).toEqual(state.data.goals[0].results);
  await page.getByRole("navigation", { name: "App navigation" }).getByRole("link", { name: "Check-in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Check-in", exact: true })).toBeVisible();
});

test("reported revenue does not invent an achievement pace or change action execution", async ({ page }) => {
  await register(page);
  const state = await snapshot(page);
  const today = dateInZone("UTC");
  const data = adaptiveWorkspace(adaptiveFixture(today, addDays(today, 4)));
  const goal = data.goals[0];
  goal.measure = { label: "Collected revenue", unit: "CAD", target: 100, baseline: 20, aggregation: "cumulative" };
  goal.target = 100;
  goal.unit = "CAD";
  goal.targetDate = addDays(today, 24);
  goal.checkpoints = [{ id: "target", date: goal.targetDate, value: 100, label: "Target result" }];
  goal.results = [20, 24, 28].map((value, i) => ({ id: `r${i}`, date: addDays(today, -4 + i * 2), value, source: "Your collected revenue report" }));
  goal.plans[0].adaptive!.steps[0].contextIds = ["morning"];
  data.memories.push({ id: "morning", text: "I prefer to outline after breakfast.", date: today });
  await seedCoaching(page, data);
  await page.goto("/app/goals/essay");
  await expect(page.getByTestId("forecast-line")).toHaveCount(0);
  const before = await page.getByRole("region", { name: "Goal and current cycle" }).innerText();
  const fresh = await snapshot(page);
  fresh.data.goals[0].results[2].value = 44;
  await save(page, fresh.data, fresh.revision);
  await page.reload();
  await expect(page.getByRole("region", { name: "Goal and current cycle" })).toHaveText(before, { useInnerText: true });
  await expect(page.locator(".projection-heading")).toContainText("44 / 100 CAD");
  await page.getByRole("button", { name: "Start action", exact: true }).click();
  await page.locator(".next-step-card").getByRole("link", { name: "Continue in Check-in" }).click();
  await expect(page.getByLabel("Message Adler")).toContainText("check in");
  await expect(page.locator(".outcome-option")).toHaveCount(0);
  expect((await snapshot(page)).data.actions[0].outcome).toBeUndefined();
  expect((await snapshot(page)).data.memories[0].text).toContain("breakfast");
});
