import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("the mountain scroll converges from a large chart to one point and keeps the first step accessible", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/");
  const finale = page.locator(".mountain-finale");
  await expect(finale).toHaveAttribute("data-scene", "summit");
  await page.evaluate(() => { document.documentElement.style.scrollBehavior = "auto"; });
  await page.evaluate(() => { const el = document.querySelector(".mountain-finale")!; window.scrollTo(0, el.getBoundingClientRect().top + scrollY); });
  await expect(finale.locator(".mountain-summit-copy")).toHaveCSS("opacity", "1");
  await expect(finale.locator(".mountain-start-copy")).toHaveAttribute("inert", "");
  const series = finale.locator(".mountain-series");
  const start = (await series.boundingBox())!;
  await page.evaluate(() => { const el = document.querySelector(".mountain-finale")!; window.scrollTo(0, el.getBoundingClientRect().top + scrollY + (el.clientHeight - innerHeight) * .55); });
  await expect(finale).toHaveAttribute("data-scene", "converging");
  const middle = (await series.boundingBox())!;
  expect(middle.width).toBeLessThan(start.width * .6);
  expect(middle.width).toBeGreaterThan(start.width * .3);
  await page.evaluate(() => { const el = document.querySelector(".mountain-finale")!; window.scrollTo(0, el.getBoundingClientRect().top + scrollY + el.clientHeight - innerHeight); });
  await expect(finale).toHaveAttribute("data-scene", "start");
  expect((await series.boundingBox())!.width).toBeLessThan(1);
  await expect(finale.locator(".mountain-start-copy")).not.toHaveAttribute("inert", "");
  await expect(finale.getByRole("heading", { name: "Let’s give it a start." })).toBeInViewport();
  await expect(finale.getByRole("link", { name: "Take your first step" })).toHaveAttribute("href", "/app/goals/new");
  const point = (await finale.locator(".mountain-start-point").boundingBox())!;
  expect(point.width).toBeLessThan(15);
  expect(Math.abs(point.x + point.width / 2 - 720)).toBeLessThan(1);
  expect(point.y).toBeGreaterThan(300);
  expect(point.y + point.height).toBeLessThan(600);
  await expect(page.locator(".footer-bottom .canada-note")).toHaveText("🇨🇦 Proudly built in Canada");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await expect(finale).toHaveAttribute("data-scene", "static");
  expect((await series.boundingBox())!.width).toBeGreaterThan(390);
  await expect(finale.locator(".mountain-start-copy")).not.toHaveAttribute("inert", "");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
});
