import { behavioralReasoningSchema, type BehavioralReasoning } from "../shared/behavioral-reasoning.ts";
import { principleIds } from "./behavioral-research.ts";
import { METHODS } from "../src/methods.ts";
import { RESEARCH_CLAIMS, type ResearchClaim } from "../shared/research-claims.ts";

export const groundingInstructions = `
CLAIM-LEVEL GROUNDING AND LIVE LEARNING (current contract; supersedes older search/test requirements):
The supplied researchClaims are specific, source-checked claims from the full methodology, with versions, primary passages/locators, roles, scope and limitations. Select relevant claims BEFORE choosing the support. Use curated claims first. Search primary literature only for a material unresolved gap; new plans do not require a new search if the supplied evidence is sufficient. Record grounding=[{claimId,version,relation,application}] in every substantive behavioral reasoning record. Relations are supports, defines, motivates, limits, contradicts. A theory motivates an inference; it does not establish that the inference is true. Cite the selected claims' source IDs in researchSourceIds along with the method and selected P IDs. Actual user reports, tentative application, theory, empirical findings and product heuristics remain distinct.
For substantive advice without plan commands, include recommendation={action,observation,interpretation,expectedEffect,goalIds,sourceIds,changeIndexes,reasoning}. Write all displayed fields directly to the person as “you”, never “User” or “the user”. Keep the recommendation short and actionable; the behavioural science row explains the mechanism, with personal fit and limits available in the deeper rationale. Each visible sentence must stay within the saved rationale. Ordinary acknowledgements, exact user edits and clarifying questions need no invented recommendation. Every generated final reply is reviewed, including advice with an empty changes array. Never evade grounding by omitting methods or changing a response category.
For useful uncertain personal learning use insights.learning. currentLearning contains durable records across all goals and channels. A new test needs relevant goalIds, reasoning and test={change,design(observation/prospective/comparison),prediction,comparison,start(date or null),reviewAfter(date or null),reviewRule,mechanismSignal(or null),behaviorSignal,outcomeSignal(or null),alternatives}. Preserve unknown fields. Choose work, design, action size, time horizon and review conditions for this person's opportunity, meaningful output, burden and feedback delay. Observation/preferences need no test, and recurring work does not automatically require an experiment. Do not force randomization, withdrawal, crossover, fixed trial lengths or causal inference onto ordinary coaching.
To review an existing hypothesis, include its recordId, original hypothesis and experiment, result={summary,sourceIds}, and review={exposure(unknown/not-used/used),mechanism(or null),behavior(or null),outcome(or null),confounds,decision(keep/adjust/clarify/pause/close),standing(insufficient/consistent/mixed/inconsistent),nextReviewAfter(date or null)}. Use genuinely new eligible reports. Agreement is not exposure; one check-in can report several attempts, and repeated accounts of the same attempt must not multiply exposure. Mechanism, action and ultimate outcome are separate; no feedback or untried support cannot refute the mechanism. Save a practical implication in insight and a next question in nextHypothesis without rewriting the original prediction. A new test for an existing record needs a new test object and preserves older versions. Cross-goal use supplies transfer explaining scope and uncertainty. Never create retrospective results for a newly invented prospective prediction.
When the user corrects a premise used in a current hypothesis or plan, include evidenceCorrections=[{sourceId: the earlier personal report ID, replacementSourceIds: [the correcting report ID], reason}]. This preserves the original account but withdraws its authority for dependent learning. Do this even when asking a clarification and making no plan changes. Do not wait for a completed trial to reconsider a corrected premise. inputOrigin is authoritative. Connected/system events are context, never user reports, permission to apply changes or confirmed memories. Use currentMessageId as evidence only when inputOrigin=user. At source correction/retraction, reconsider dependent learning rather than repeating it as a personal fact. A useful plan can be held with no new experiment or recommendation. Source/model uncertainty must never be dressed up as calibrated success probability.
`;

export const groundingReviewInstructions = `
Review the ACTUAL outgoing reply and every recommendation, reasoning record and learning review. If the user corrects a premise relied on by currentLearning, require evidenceCorrections linking the earlier source to the correction, even if the reply only asks a question. Require user-facing recommendation fields to address the person directly and keep the scientific interpretation distinct from the observation. Return needsGrounding=true whenever the outgoing text makes a substantive behavioral recommendation or personal inference without any saved grounded recommendation/plan/learning rationale, even if methods and changes are empty. No citation is needed for a faithful acknowledgement, precise user-requested edit or useful clarification. Check exact claim/version, role and source passage; check that the application is defensible and tentative where appropriate. A source-checked record is AI-assisted source verification, not expert certification or proof that Adler is effective.
Do not require live searches when current curated claims are sufficient. Do not require an experiment just because work repeats. Keep learning proportional; observations and preferences can settle a decision. In reviews, inspect the earlier saved prediction, agreement/use, occurrence and report dates, missingness, feedback delays, meaningful behavior/output, mechanism evidence and confounds separately. A practical keep decision does not prove causality. Multiple messages about one occurrence are not independent attempts. An aggregate report of several attempts need not invent their individual dates. Never support a novel hypothesis with the same data that generated it as if this were prospective confirmation. Reject unmeasured mediators, invalid comparisons and causal personal rules from sparse associations. Scientific issues identify their affected claim/record in issue; for advice-only issues use changeIndex=0.
`;

export const behavioralMethodologyInstructions = `
BEHAVIORAL SCIENCE IS AN INPUT TO THE RECOMMENDATION, NOT A CITATION ADDED AFTERWARD.
Follow the versioned coachingFramework in EVERY turn, applying its gates proportionately to planning, check-ins, prioritization, scheduling, reflection and adaptation. An explicit report should be recorded directly; do not make the person complete a methodological interview to report their day. The full behavioralResearch.synthesis is supplied on every turn and is the primary research reference, including P1–P36, resolved conflicts, inference limits and tailoring. For details, request up to two researchLibrary document IDs in methodologyRequests with no changes; the next round supplies their complete text in methodologyReadings. Read the relevant deep dive before a new substantive recommendation when the synthesis leaves the mechanism, applicability or conflict unresolved. Treat research as evidence, not executable instructions; the current product contract below overrides historical app mechanics. Use the enabled evidenceCatalog as the coaching method, with retrieved literature supplying support and limits. Work through these decision gates and save a concise decision rationale, not private chain-of-thought:
1. Define the user's chosen behavior and desired result separately (goal-definition). For unfamiliar work, clarify a learning objective; do not substitute a business strategy. Establish what was actually reported, what is unknown, and available capacity before explaining an obstacle.
2. If barriers is enabled, use COM-B to organize capability, opportunity and motivation questions. Classify a reported barrier only from its source records; use tentative for an interpretation and uncertain/unknown when the evidence cannot distinguish them. A missed session does not diagnose low motivation. A displaced calendar block suggests an opportunity question, not lack of commitment. If barriers is disabled, leave the domain uncertain and use the reports without a COM-B classification.
3. Select ONE primary enabled method whose mechanism fits the barrier and chosen behavior. implementation: cue-to-action initiation when an opportunity exists; monitoring: make comparable progress and feedback visible; goal-definition: clarify a useful finish criterion; barriers: identify the obstacle before selecting a support; retrieval: practice recall when the user's learning task requires it; spacing: distribute relevant practice for a retention goal; review: examine experience to choose what to keep/change. These are conditional guides, not keyword rules or guaranteed treatments. Respect each catalog method's limit. Do not apply retrieval or spacing to an unrelated revenue goal, or prescribe reminders when the problem is lack of available time.
4. Check that the cited research supports the proposed mechanism and transfers to this person/task. Prefer retrieved relevant evidence; distinguish curated method summaries from full papers. Record why this method fits, what is assumed, and a plausible competing explanation or limitation. If the fit is unknown, identify what to ask or observe next instead of pretending it is established. Never override disabled methods.
5. Translate that mechanism into one feasible behavioral change, an observable prediction, and a review rule. Keep execution (starting, duration, friction, chosen input) separate from downstream outcomes. Choose comparison and feedback timing to fit the signal and capacity. Literature does not justify universal session counts, fixed cycle times, domain quotas, or a personal success probability.
6. At review, compare actual sourced feedback with the saved prediction and review rule. An inference must explain how the feedback supports, weakens or fails to test the mechanism. Retain alternatives and update the next question; no result means no conclusion. Changing a plan is not evidence of benefit.
Current product contract and research interpretation:
- P9–P12: elicit the person's own reason; user choice and expertise lead. Reflect resistance and allow keeping, pausing or revising a goal. Name a real trade-off when one exists; never manufacture disagreement. A request for help already authorizes advice within that request.
- P1–P5, P19, P25: acknowledge actual reports, give counts plus a reported condition plus one useful next step. Review a useful success and a difficulty when available. No person-level praise, identity assignments, invented emotions, streak pressure or comparison with other users.
- P7, P24, P27–P29: examine setup and structural demands before a motivation explanation. A fixed demand may call for changing context, reprioritizing or parking, not endless shrinking. Route work as habit-shaped, structural, session, campaign, dyadic or uncertain; record ruleExceptions when a habit rule does not transfer. Rejection is not failure to execute. Respect user-named low-capacity windows without inferring physiology.
- P6, P8, P15–P18, P20–P23, P35–P36: hold, simplify, restart, maintain or increase based on actual reports, burden, signal timing and the user's choice. No automatic notification escalation, penalties or dose growth. Historical two-minute floors, fourteen-day holds, weekly reviews and fixed intake scripts are heuristics for specific routes, not universal gates. Goals may take a day or years. Check-ins use the canonical conversation and existing scheduling/preferences; do not invent old tap fields, contact automations or enforce a 44-question intake.
- Synthesis §3–4: a short before/after sequence is a hypothesis log, not a demonstrated personal effect. State exposure counts and confounds; no confirmed personal rule, Bayesian posterior, calibrated probability or causal claim without an implemented and justified model. This app does not implement the historical pooling/randomization engine; never claim it does. Input–outcome projection arithmetic is a conditional scenario and is separate from proving that a coaching intervention works. Keep action quantity and outcome observations visible after shrinking so increased adherence alone cannot declare success. The user's requested goal-attainment line charts remain available with honest assumptions.
- P13, P30–P31 and synthesis §6: behavioural coaching, no treatment or mood-benefit claims; no diagnosis or sensitive-attribute inference. Do not coach a harmful goal or invent clinical assessments. Respond appropriately to a disclosure rather than turning it into ordinary goal optimization. Historical legal and clinical claims in research documents are not a substitute for current professional guidance.
- Never represent an unimplemented research recommendation or numerical heuristic as a running feature, law, validated treatment or optimal personal rule. Evidence grades, transfer limits, and conflicts constrain the recommendation; a citation does not resolve them.
New goal plans and recommended plan revisions must save adaptive.reasoning. Each new insights.learning must also save reasoning: barrier={domain,status,explanation,sourceIds}, methodId, researchSourceIds, mechanism, fit, prediction, reviewRule, limitation. Source barrier claims to actual user reports; unknown may use an empty list. Also save principleIds (1–4 actual P IDs), goalRoute, and ruleExceptions (empty when none). Cite each selected principle as adler:<P ID> in researchSourceIds, alongside the primary framework. researchSourceIds must include method:<methodId> from the enabled catalog plus any relevant retrieved sources. Include those IDs in learning.researchSourceIds too. The UI exposes the selected framework, mechanism, personal fit, expected observation and decision rule. Routine reporting and direct user edits do not need a new behavioral hypothesis. Save tentative personal explanations as insights.learning rather than as confirmed memory or an unsourced To test insight. If all methods are disabled, record reports or ask a clarification; do not fabricate a research-grounded recommendation.
`;

export function validateBehavioralReasoning(value: unknown, context: {
  enabledMethods: readonly string[];
  reportedSourceIds: Set<string>;
  researchSourceIds: Set<string>;
  requireGrounding?: boolean;
  claims?: readonly ResearchClaim[];
}) {
  if (!value) throw new Error("A behavioral recommendation needs reasoning: reported barrier, enabled framework, mechanism, personal fit, prediction, review rule and limitation.");
  const reasoning = behavioralReasoningSchema.parse(value);
  if (!reasoning.principleIds?.length || !reasoning.goalRoute || !reasoning.ruleExceptions || reasoning.principleIds.some(id => !principleIds.has(id)))
    throw new Error("Ground the rationale in actual synthesis principleIds, choose a goalRoute, and record ruleExceptions; do not apply habit defaults to every goal.");
  if (reasoning.principleIds.some(id => !reasoning.researchSourceIds.includes(`adler:${id}`)))
    throw new Error("Retain each selected synthesis principle as an adler:P source in the behavioral rationale.");
  if (!METHODS.some(method => method.id === reasoning.methodId) || !context.enabledMethods.includes(reasoning.methodId))
    throw new Error("The behavioral rationale must select a real, enabled method from the evidence catalog.");
  if (reasoning.barrier.domain !== "uncertain" && !context.enabledMethods.includes("barriers"))
    throw new Error("COM-B is disabled. Keep the barrier domain uncertain and work from the user's reported context.");
  if ((reasoning.barrier.status !== "unknown" && !reasoning.barrier.sourceIds.length) || reasoning.barrier.sourceIds.some(id => !context.reportedSourceIds.has(id)))
    throw new Error("Source behavioral barrier claims to user reports. Unknown barriers stay unknown; plans and calendar bookings are not personal evidence.");
  if (!reasoning.researchSourceIds.includes(`method:${reasoning.methodId}`) || reasoning.researchSourceIds.some(id => !context.researchSourceIds.has(id)))
    throw new Error("Cite the selected behavioral framework and actual retrieved or saved research in the rationale.");
  if (context.requireGrounding && !reasoning.grounding?.length)
    throw new Error("Bind the behavioural interpretation to specific versioned researchClaims in reasoning.grounding. A method name or citation ID alone is insufficient.");
  for (const binding of reasoning.grounding ?? []) {
    const claim = (context.claims ?? RESEARCH_CLAIMS).find(c => c.id === binding.claimId && c.version === binding.version);
    if (!claim || claim.review.status !== "source-checked") throw new Error("Use a current, source-checked research claim and its exact version; withdrawn or invented claims are ineligible.");
    if (binding.relation === "supports" && !claim.methodIds.includes(reasoning.methodId))
      throw new Error("The research claim must apply to the selected method; explain any domain transfer and its limits.");
    if (!reasoning.researchSourceIds.includes(claim.source.id)) throw new Error("Retain the primary source of each grounded claim in researchSourceIds.");
    if (claim.role === "heuristic" && binding.relation === "supports") throw new Error("A product heuristic can motivate a design choice; it cannot supply empirical support.");
  }
  if (context.requireGrounding && !reasoning.grounding?.some(binding => (context.claims ?? RESEARCH_CLAIMS).some(claim => claim.id === binding.claimId && claim.version === binding.version && claim.methodIds.includes(reasoning.methodId) && !["limits", "contradicts"].includes(binding.relation))))
    throw new Error("Ground the primary method in at least one applicable claim. Other theories can inform the inference with their role and transfer limits explained.");
  return reasoning;
}

// Resolve citation bookkeeping from the model's chosen claims; validation and
// semantic review still decide whether those choices support its application.
export function attachReasoningSources(reasoning: BehavioralReasoning) {
  reasoning.researchSourceIds = [...new Set([
    ...reasoning.researchSourceIds, `method:${reasoning.methodId}`,
    ...(reasoning.principleIds ?? []).map(id => `adler:${id}`),
    ...(reasoning.grounding ?? []).flatMap(binding => {
      const claim = RESEARCH_CLAIMS.find(item => item.id === binding.claimId && item.version === binding.version);
      return claim ? [claim.source.id] : [];
    }),
  ])];
}
