// The product's behavioral decision gates. Evidence and limits live in METHODS;
// this is Adler's application of those principles, not a validated intervention.
export const WORK_HIERARCHY = `A goal is the desired overall result. A milestone is a subgoal: an intermediate outcome such as a first book finished, a draft ready for feedback, or a first paying client. An action is a concrete input the person controls and can execute and report: read 20 pages, write for 30 minutes, or send one application. Specify the work and its meaningful amount, duration or discrete execution; do not disguise an outcome like "win a client" or "finish the manuscript" as an action. An action can be one-time or repeating. Its completion criterion tests the input, never another person's response or the milestone outcome. Use the saved measure for pages/counts and actualMinutes for time; durationMinutes alone is a planning budget, not a report that time was spent. One action may support successive milestones. Action reports never automatically verify a milestone. Choose useful input quantities from the person's context and capacity without inventing domain quotas or a guaranteed input-to-outcome conversion.`;

export const COACHING_FRAMEWORK = {
  version: "besci-coaching-v2.1",
  researchCommit: "472e979",
  researchPath: "docs/research/behavioural-science-synthesis.md",
  workHierarchy: WORK_HIERARCHY,
  stages: [
    { id: "define", principleIds: ["P9", "P10", "P11", "P12", "P29"], methods: ["goal-definition"], question: "What matters to this person, and what can they control?", rule: "Preserve the user-owned outcome and horizon. Save a requested goal even before its work is chosen; an unplanned draft is not an experiment. Milestones are intermediate results, distinct from the concrete user inputs that contribute to them. Clarify only what changes useful behavioural support; do not invent domain strategy." },
    { id: "observe", principleIds: ["P1", "P3", "P4", "P5", "P25"], methods: ["monitoring"], question: "What do their reports and constraints actually establish?", rule: "Use dated observations, competing goals and available capacity. Missing reports remain unknown; calendar context is not proof of work. Record explicit reports without forcing a new experiment." },
    { id: "understand", principleIds: ["P7", "P16", "P24", "P27", "P28"], methods: ["barriers"], question: "Which barrier is reported, and what remains uncertain?", rule: "Use COM-B capability, opportunity and motivation as questions, not diagnoses. Attendance alone cannot identify a cause. If the framework is disabled or evidence cannot distinguish barriers, keep the domain uncertain." },
    { id: "select", principleIds: ["P2", "P8", "P20", "P29"], methods: ["goal-definition", "implementation", "monitoring", "barriers", "retrieval", "spacing", "review"], question: "Which supported mechanism fits this behavior and person?", rule: "Choose applicable versioned research claims before selecting a primary enabled method. Preserve evidence role, passage, source access, mechanism, personal fit and limits; use live primary research for a consequential unresolved gap. Cues require a viable opportunity. Retrieval and spacing require a relevant learning task. Research cannot choose business channels or establish personal outcome returns." },
    { id: "design", principleIds: ["P2", "P8", "P10", "P24", "P29"], methods: ["implementation", "goal-definition", "monitoring", "review"], question: "What is the smallest useful change, and how will we know whether it helps?", rule: "Translate the mechanism into feasible work, a cue or support, fallback, observable prediction, comparison and review rule. Match cycle, measurement and feedback timing to the person and signal. Respect capacity across goals and keep consequential changes reviewable." },
    { id: "learn", principleIds: ["P3", "P6", "P14", "P18", "P24"], methods: ["monitoring", "review"], question: "What does the feedback support, and what should change next?", rule: "Compare reported feedback with the saved prediction and decision rule. Separate execution improvement from outcome response; retain alternative explanations and feedback lag. Keep, adjust, clarify or pause; preserve immutable evidence revisions, the current hypothesis and pending suggestions separately. Correction or source withdrawal requires reconsideration. No feedback means no conclusion." },
  ],
  groundingPolicy: "grounded-coaching-v2",
  evidence: "Full P1–P36 synthesis and referenced deep dives plus scoped versioned claims. Semantic review checks the actual outgoing advice; source checking is not expert certification.",
  scope: "All coaching channels and goal horizons. Apply relevant gates proportionately: a factual check-in does not need a new plan, and a scheduling preference does not need a personality inference.",
} as const;
