export const integrationCategories = [
  "All",
  "AI & assistants",
  "Calendars",
  "Messages",
  "Health & fitness",
  "Tasks & notes",
  "Learning",
  "Automation",
] as const;
export interface Integration {
  id: string;
  name: string;
  category: (typeof integrationCategories)[number];
  icon: string;
  description: string;
  detail: string;
  status: "Planned" | "Setup available";
  route?: string;
}
const planned = (
  id: string,
  name: string,
  category: Integration["category"],
  icon: string,
  description: string,
  detail: string,
): Integration => ({
  id,
  name,
  category,
  icon,
  description,
  detail,
  status: "Planned",
});
export const integrations: Integration[] = [
  planned(
    "chatgpt",
    "ChatGPT",
    "AI & assistants",
    "chatgpt.svg",
    "Work on your Adler goals from a ChatGPT conversation.",
    "A planned chat connection to read your goals, record updates, and review plan changes through Adler’s shared coaching system.",
  ),
  planned(
    "claude",
    "Claude",
    "AI & assistants",
    "claude.svg",
    "Bring your goals and coaching program into Claude.",
    "A planned assistant connection for working with the same goals, actions, and records you see in Adler. Compatible MCP clients can already use the MCP endpoint below.",
  ),
  planned(
    "gemini",
    "Gemini",
    "AI & assistants",
    "gemini.svg",
    "Continue working with Adler from Gemini.",
    "A planned connection to the Gemini chat app. Using a Gemini API key to power Adler is already supported through AI model settings.",
  ),
  {
    id: "models",
    name: "GPT, Claude & Gemini APIs",
    category: "AI & assistants",
    icon: "gemini.svg",
    description: "Choose the model that powers your coach.",
    detail:
      "Add an OpenAI, Anthropic, or Gemini API key. Adler’s goals, command system, and coaching program stay the same when you switch providers.",
    status: "Setup available",
    route: "/app/settings/provider",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "Calendars",
    icon: "google-calendar.png",
    description: "Find free time and book work with a check-in afterward.",
    detail:
      "Read selected calendars for availability and review a time before booking. Google OAuth must be configured for this deployment.",
    status: "Setup available",
    route: "/app/calendar",
  },
  {
    id: "apple-calendar",
    name: "Apple Calendar",
    category: "Calendars",
    icon: "apple-calendar.png",
    description: "Fit your goal sessions around your existing commitments.",
    detail:
      "Connect iCloud Calendar using an app-specific password, check availability, and confirm a work block with an optional check-in.",
    status: "Setup available",
    route: "/app/calendar",
  },
  planned(
    "outlook",
    "Microsoft Outlook",
    "Calendars",
    "outlook.png",
    "Fit goal sessions around your work calendar.",
    "A planned calendar connection to check availability across selected Outlook calendars and review work blocks before booking.",
  ),
  {
    id: "imessage",
    name: "iMessage",
    category: "Messages",
    icon: "imessage.png",
    description: "Text your coach, react to replies, and update your plan.",
    detail:
      "The iMessage adapter uses the same coaching and action service as the app. Sending requires a configured messaging provider and a paired phone number.",
    status: "Setup available",
    route: "/app/connections",
  },
  {
    id: "sms",
    name: "SMS",
    category: "Messages",
    icon: "sms",
    description: "Check in by text from any phone.",
    detail:
      "The same goals and coach through ordinary text messages. SMS delivery requires a configured messaging provider and phone pairing.",
    status: "Setup available",
    route: "/app/connections",
  },
  planned(
    "whatsapp",
    "WhatsApp",
    "Messages",
    "whatsapp.svg",
    "Send a quick update from your everyday messaging app.",
    "A planned messaging connection for check-ins, goal creation, and reviewing changes from WhatsApp.",
  ),
  planned(
    "telegram",
    "Telegram",
    "Messages",
    "telegram.svg",
    "Keep your coach one message away.",
    "A planned Telegram conversation connected to your Adler workspace.",
  ),
  planned(
    "slack",
    "Slack",
    "Messages",
    "slack.svg",
    "Keep work goals close to where your day happens.",
    "A planned private coaching conversation for work goals, check-ins, and weekly reviews.",
  ),
  planned(
    "discord",
    "Discord",
    "Messages",
    "discord.svg",
    "Talk to Adler from a private conversation.",
    "A planned messaging connection using your existing Adler goals and program.",
  ),
  planned(
    "strava",
    "Strava",
    "Health & fitness",
    "strava.svg",
    "Bring recorded runs and rides into your goal progress.",
    "A planned activity import. Adler would use actual distance and activity records as evidence, keeping completed sessions separate from achieving your goal.",
  ),
  planned(
    "apple-health",
    "Apple Health",
    "Health & fitness",
    "apple-health.png",
    "Connect the activity data relevant to your personal goals.",
    "A planned connection for activity and workout measurements you choose to share. This would require a native Apple app and explicit permissions for each data type.",
  ),
  planned(
    "garmin",
    "Garmin",
    "Health & fitness",
    "garmin.svg",
    "Use recorded workouts to inform your next review.",
    "A planned import of selected workout measurements, with their source and date visible in Adler.",
  ),
  planned(
    "fitbit",
    "Fitbit",
    "Health & fitness",
    "fitbit.svg",
    "See your activity alongside the goals you’re working on.",
    "A planned activity connection for reviewing reported results without re-entering them by hand.",
  ),
  planned(
    "oura",
    "Oura",
    "Health & fitness",
    "oura.png",
    "Bring selected activity and recovery context into your planning.",
    "A planned connection for the measurements you choose to share. Adler would keep reported data separate from explanations that still need testing.",
  ),
  planned(
    "notion",
    "Notion",
    "Tasks & notes",
    "notion.svg",
    "Connect your goals with the notes and projects behind them.",
    "A planned link to selected pages, project notes, and deliverables so a goal’s supporting work is easier to find.",
  ),
  planned(
    "todoist",
    "Todoist",
    "Tasks & notes",
    "todoist.svg",
    "Keep next actions aligned with your daily task list.",
    "A planned task sync to reduce duplicate entry. Finishing a task would remain separate from verifying a goal milestone.",
  ),
  planned(
    "apple-reminders",
    "Apple Reminders",
    "Tasks & notes",
    "apple-reminders.png",
    "Keep your next step in the list you already use.",
    "A planned connection for selected actions and reminders, keeping their goal and completion status linked.",
  ),
  planned(
    "obsidian",
    "Obsidian",
    "Tasks & notes",
    "obsidian.svg",
    "Link the notes and reflections that inform your plan.",
    "A planned connection to selected personal notes, with their source visible when they inform a recommendation.",
  ),
  planned(
    "duolingo",
    "Duolingo",
    "Learning",
    "duolingo.svg",
    "Put language practice in the context of your learning goal.",
    "A planned learning activity connection. Practice time would be tracked separately from your ability to use the language.",
  ),
  planned(
    "anki",
    "Anki",
    "Learning",
    "anki.svg",
    "Review practice activity alongside what you can recall.",
    "A planned connection for selected study and recall records, using comparable measures instead of treating a streak as mastery.",
  ),
  {
    id: "mcp",
    name: "MCP",
    category: "Automation",
    icon: "modelcontextprotocol.svg",
    description: "Give compatible AI tools access to your Adler workspace.",
    detail:
      "A shared MCP endpoint exposes coaching, workspace records, proposals, and approvals. Use a personal token with a compatible client; chat app support varies.",
    status: "Setup available",
    route: "/app/connections",
  },
  {
    id: "webhooks",
    name: "Webhooks",
    category: "Automation",
    icon: "webhook",
    description: "Send updates from tools you’ve connected yourself.",
    detail:
      "Authenticated incoming events can enter the same coaching service. Configure a personal token and only send the records you want your coach to use.",
    status: "Setup available",
    route: "/app/connections",
  },
  planned(
    "zapier",
    "Zapier",
    "Automation",
    "zapier.svg",
    "Connect Adler with your other everyday tools.",
    "A planned catalog of triggers and actions for moving approved updates between Adler and other apps.",
  ),
  planned(
    "googlesheets",
    "Google Sheets",
    "Automation",
    "googlesheets.svg",
    "Connect the results you already track in a spreadsheet.",
    "A planned import and export of selected goal measurements, preserving dates and sources.",
  ),
];
