// Shared by the animated landing journey and its saved fictional workspace.
export const portfolioStory = {
  observation: "I had 25 minutes to write, but kept picking up my phone and scrolling. I don't need it for work or urgent calls during that time; I can leave it in the kitchen.",
  suggestion: "Before writing, leave your phone in the kitchen. Keep the same 25-minute session at 8:30 on Tuesdays and Thursdays.",
  rationale: "Putting the phone in another room may reduce the pull to check it while you write.",
  shortRationale: "Change the setup so you have fewer distractions to resist.",
  science: "Situation modification changes the surroundings before a distraction competes with the work you chose.",
  method: "Situation modification",
  methodId: "barriers",
  principleId: "P7",
  claimIds: ["claim:com-b-opportunity", "claim:situational-modification-student-trials"],
  researchUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4856169/",
  researchTitle: "Duckworth et al. · A Stitch in Time",
  researchFinding: "In two short field experiments, students asked to change their surroundings reported better study-goal attainment than comparison groups. This does not establish that moving your phone will help your writing.",
  researchGrade: "B / moderate for these student experiments. Self-reported results over one week; transfer to adult portfolio work and Adler remains uncertain. COM-B supplies a theoretical distinction, not evidence of effectiveness.",
  prediction: "With the phone in the kitchen, you report fewer phone checks and more time writing within the same 25-minute session.",
  followUp: "Did the phone stay in the kitchen? Did you check it, and how many minutes did you write?",
  feedback: "On October 13 and 15, my phone stayed in the kitchen. I didn't check it and wrote for 25 minutes both times. Staying focused felt easier. Neither session finished another case study.",
  reviewSummary: "You reported leaving the phone in the kitchen, not checking it, and writing for 25 minutes in both trial sessions.",
  implication: "Keep the phone in the kitchen during the next writing sessions. Both reported trials went as intended, but the work and demands on your attention may differ next time.",
  limitation: "Two reports support trying this again, not a proven personal rule. A writing session does not establish a published case study.",
  testLimitation: "This is a testable possibility, not a proven personal rule. Work difficulty, available time and the need to be reachable can change.",
  originalAction: "Write for 25 minutes at 8:30.",
  revisedAction: "Leave your phone in the kitchen. Write for 25 minutes at 8:30.",
  trialDates: ["2026-10-13", "2026-10-15"],
  reviewDate: "2026-10-19",
  nextReviewDate: "2026-10-25",
  booking: { date: "2026-10-20", time: "8:30–8:55", label: "Tuesday, October 20" },
} as const;

// The text thread and fixture use identical reports, proposals and confirmations.
export const portfolioConversation = [
  { phase: 0, id: "portfolio-missed-report", role: "user", at: "2026-10-10T13:58:00Z", text: "I had time to write on October 1, but spent it scrolling on my phone." },
  { phase: 1, id: "portfolio-time-question", role: "coach", at: "2026-10-10T13:59:00Z", text: "Do you need your phone for the work, or to be reachable during those 25 minutes?" },
  { phase: 2, id: "portfolio-editing-report", role: "user", at: "2026-10-10T14:00:00Z", text: "No. I can leave it in the kitchen while I write." },
  { phase: 3, id: "portfolio-suggestion", role: "coach", at: "2026-10-12T12:00:00Z", text: `${portfolioStory.suggestion}\n\n${portfolioStory.rationale}\n\nTry it October 13 and 15, then review on October 19?` },
  { phase: 4, id: "portfolio-agreement", role: "user", at: "2026-10-12T12:01:00Z", text: "Yes, let’s try it." },
  { phase: 5, id: "portfolio-review-question", role: "coach", at: "2026-10-19T17:00:00Z", text: portfolioStory.followUp },
  { phase: 5, id: "portfolio-review-report", role: "user", at: "2026-10-19T17:05:00Z", text: portfolioStory.feedback },
  { phase: 6, id: "portfolio-kept-plan", role: "coach", at: "2026-10-19T18:00:00Z", text: "You wrote for 25 minutes both times without checking your phone. Two reports are encouraging, but early. Keep the phone in the kitchen next week and review October 25?" },
  { phase: 7, id: "portfolio-continue-agreement", role: "user", at: "2026-10-19T18:01:00Z", text: "Yes, keep that in my writing plan." },
  { phase: 8, id: "portfolio-today-question", role: "user", at: "2026-10-20T11:55:00Z", text: "What do I have to do today?" },
  { phase: 9, id: "portfolio-today-reply", role: "coach", at: "2026-10-20T11:56:00Z", text: "Two actions today:\nPortfolio: 25 min at 8:30. Phone in the kitchen.\nReading: 20 pages after lunch." },
  { phase: 10, id: "portfolio-progress-question", role: "user", at: "2026-10-20T11:57:00Z", text: "Am I on track with my portfolio?" },
  { phase: 10, id: "portfolio-progress-reply", role: "coach", at: "2026-10-20T11:57:30Z", text: "Your first milestone is done: 1 of 3 case studies published. Next: case study 2 by November 1.\n\nI need a new publication report to update the outlook for this plan." },
  { phase: 11, id: "portfolio-booking-request", role: "user", at: "2026-10-20T11:58:00Z", text: "Book today’s portfolio session." },
  { phase: 11, id: "portfolio-booking-time", role: "coach", at: "2026-10-20T11:58:15Z", text: "8:30–8:55 is available. Book it in Google Calendar?" },
  { phase: 12, id: "portfolio-booking-confirmed", role: "user", at: "2026-10-20T11:58:45Z", text: "Yes, book it." },
  { phase: 12, id: "portfolio-booking-reply", role: "coach", at: "2026-10-20T11:59:00Z", text: "Booked for 8:30–8:55." },
] as const;
